---
- name: Install epel-release
  yum:
    name: epel-release

- name: Test for EPEL rpmkeys
  shell: 'rpm -q gpg-pubkey-352c64e5-52ae6884'
  args:
    warn: no
  changed_when: no
  ignore_errors: yes
  register: epel_rpmkeys

- name: Install EPEL rpmkeys
  shell: >-
    package='epel-release'
    && key='/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7'
    && [[ "$(rpm -qf --queryformat='%{NAME}\n' "${key}")" = "${package}" ]]
    && rpm -qV "${package}" | awk -v key="${key}" '$NF == key { exit 1 }'
    && rpmkeys --import "${key}"
  when: epel_rpmkeys|failed
